<!DOCTYPE html>
<html>

    <head>
        <title>Error</title>
        <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport"
			content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
		<meta name="description" content="绿茶浏览器数据后台">
		<meta name="author" content="zerob13">
        <link rel="stylesheet" type="text/css" href="/css/screen.css" />
        <script type="text/javascript" src="/js/main.js"></script>
    </head>
    <body>
        <h1>Application Error:</h1><?php echo ($message) ? '<pre>'.$message.'</pre>' : ''; ?>
        <p> <a href="/">重新登陆</a></p>
    </body>
</html>