							<script src="../assets/urlissuecate.js"></script>
							<div class="block">
							<div class="navbar navbar-inner block-header">
								<div class="muted pull-left">左屏导航</div>
								<div class="pull-right">
									<span class="badge badge-info">最后修改日期: 2014-4-1 14:11</span>
								</div>
							</div>
							<div class="block-content collapse in">
								<table class="table table-striped">
									<thead>
										<tr>
											<th><button class="btn btn-small btn-info"
													data-toggle="modal" data-target="#myModal" id="add">添加</button></th>
											<th>类别关键字</th>
											<th>类别名称</th>
											<th>操作</th>
										</tr>
									</thead>
									<tbody>
									<?php foreach ($urlissueCate as $k=>$v){?>
										<tr>
											<td><?=$v['id']?></td>
											<td><?=$v['cate_key']?></td>
											<td><a href="/core/urlissueitem?cate_key=<?=$v['cate_key']?>"><?=$v['describe']?></a></td>
											<td>
												<button class="btn btn-small btn-primary btn-modify"
													data-toggle="modal" data-target="#myModal" id="update">修改</button>
												<button class="btn btn-small btn-danger" id="del">删除</button>
											</td>
										</tr>
									<?php }?>									
									</tbody>
								</table>
							</div>
							 <div class="pagination pagination-small pull-right">
                                 <ul>
		                             <li><a href="urlissuecate?page=<?=$nowPage-1?>">Prev</a></li>
		                             <?php if($numPages==1){?>
                                    <li class="page_btn active"><a href="urlissuecate" >1</a></li>
                                    <?php }else{?>
		                             <li class="page_btn <?php if($nowPage==1){echo "active";}?>">
		                             <a href="urlissuecate?page=1" >1</a>
		                             </li>
		                             <?php if ($nowPage>4) {?>
		                             <li><a>...</a></li>
		                             <?php }?>
		                             <?php for ($page = 2;$page < $numPages;$page ++){
											if (($page>=$nowPage-2)&&($page<=$nowPage+2)) {								
		                             	 ?>
		                             <li class="page_btn <?php if($page == $nowPage){echo "active";}?>">
		                             <a href="urlissuecate?page=<?=$page?>"><?=$page?></a>
		                             </li>
		                             <?php }}?>
		                             <?php if ($nowPage+3<$numPages) {?>
		                             <li><a>...</a></li>
		                             <?php }?>
		                             <li class="page_btn <?php if($nowPage==$numPages){echo "active";}?>">
		                             <a href="urlissuecate?page=<?=$numPages?>"><?=$numPages?></a>
		                             </li> 
		                             <?php }?>                
		                             <li><a href="urlissuecate?page=<?=$nowPage+1?>">Next</a></li>     
		                        </ul>
                            </div>
						</div>