<!DOCTYPE html>
<html class="no-js">
<head>
<title>绿茶浏览器数据后台</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
<meta name="description" content="绿茶浏览器数据后台">
<meta name="author" content="zerob13">
<!-- Bootstrap -->
<link href="../bootstrap/css/bootstrap.min.css" rel="stylesheet"
	media="screen">
<link href="../bootstrap/css/bootstrap-responsive.min.css"
	rel="stylesheet" media="screen">
<link href="../vendors/easypiechart/jquery.easy-pie-chart.css"
	rel="stylesheet" media="screen">
<link href="../assets/styles.css" rel="stylesheet" media="screen">
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<script src="../vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
<script src="../vendors/jquery-1.9.1.min.js"></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>
<script src="../vendors/easypiechart/jquery.easy-pie-chart.js"></script>
<script src="../vendors/jquery-ui-1.10.3.js"></script>
<script src="../vendors/jquery.ui.touch-punch.min.js"></script>
<script src="../assets/scripts.js"></script>
<script src="../assets/naviitem.js"></script>
</head>

<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a class="brand" href="#">数据后台</a>
				<div class="nav-collapse collapse">
					<ul class="nav pull-right">
						<li class="dropdown"><a href="#" role="button"
							class="dropdown-toggle" data-toggle="dropdown"> <i
								class="icon-user"></i>当前用户: <?=$userName?><i class="caret"></i>

						</a>
							<ul class="dropdown-menu">
								<li><a tabindex="-1" href="exit">登出</a></li>
							</ul></li>
					</ul>
					<ul class="nav">
						<li><a href="/core/version">版本号统一升级</a></li>
					</ul>
					<ul class="nav">
						<li><a href="/core/urlrecommend">网址推荐</a></li>
					</ul>
					<ul class="nav">
						<li><a href="/core/strissue">字符串下发</a></li>
					</ul>
					<ul class="nav">
						<li><a href="/core/urlissueCate">网址下发</a></li>
					</ul>
					<ul class="nav">
						<li class="active"><a href="/leftnavi/navicate">左屏导航</a></li>
					</ul>
					<ul class="nav">
						<li><a href="/lightapp/Litecategory">轻应用</a></li>
					</ul>
					<ul class="nav">
						<li><a href="/home/home">首页运营数据</a></li>
					</ul>
				</div>
				<!--/.nav-collapse -->
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span3" id="sidebar">
				<ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
					<li><a href="navicate"><i class="icon-chevron-right"></i>左屏导航父类</a>
						<ul class="nav nav-list collapse in" id="submenu">
							<?php foreach ($navicate as $k=>$v){?>
							<?php if($v['id'] == $cate_id){?>
							<li>
								<a href="/leftnavi/navisubcate?cate_id=<?=$v['id']?>"><i class="icon-chevron-right"></i><?=$v['title']?></a>
								<ul class="nav nav-list collapse in" id="submenu">
								<?php foreach ($navisubcate as $k=>$v){?>
								<li class="<?php if($v['id']==$subcate_id){echo "active";}?>"><a href="/leftnavi/naviitem?subcate_id=<?=$v['id']?>"><?=$v['title']?></a></li>
								<?php }?>
								</ul>
							</li>
							<?php }else{?>
							<li><a href="/leftnavi/navisubcate?cate_id=<?=$v['id']?>"><i class="icon-chevron-right"></i><?=$v['title']?></a></li>
							<?php }}?>
						</ul>
					</li>
<!-- 					<li><a href="leftdata"><i class="icon-chevron-right"></i>左屏条幅数据下发</a></li> -->
				</ul>
			</div>

			<!--/span-->
			<div class="span9" id="content">
				<div class="row-fluid" id="first-row">
					<!-- 这个是弹出提示，可以通过后台逻辑来控制 -->
					<!-- <div class="alert alert-success"> -->
					<!--     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> -->
					<!--     <h4>提醒</h4> -->
					<!--     数据添加成功</div> -->
				</div>
				<div class="row-fluid">
					<div class="span12">
						<!-- block -->
						<div class="block">
							<div class="navbar navbar-inner block-header">
								<div class="muted pull-left">网址数据</div>
								<div class="pull-right">
									<span class="badge badge-info">最后修改日期: 2014-4-1 14:11</span>
								</div>
							</div>
							<div class="block-content collapse in">
								<table class="table table-striped">
									<thead>
										<tr>
											<th><button class="btn btn-small btn-info"
													data-toggle="modal" data-target="#myModal" id="add">添加</button>
												<button class="btn btn-small btn-info" id="sort_btn">排序</button>
											</th>
											<th>网址名称</th>											
											<th>所属子类</th>
											<th>网址URL</th>
											<th>操作</th>
										</tr>
									</thead>
									<tbody class="drag_tr">
									<?php foreach ($naviitem as $k=>$v){?>
										<tr>
											<td>
												<span class="label label-default drag_holder">点我拖动</span>
												<p><?=$v['id']?></p>
											</td>
											<td><?=$v['title']?></td>
											<td>
											<input type='hidden' value='<?=$v['subcate_id']?>' id='subcate_id'>
											<input type='hidden' value='<?=$v['a_color']?>' id='a_color'>
											<input type='hidden' value='<?=$v['b_color']?>' id='b_color'>
											<?php
											foreach ($navisubcate as $k_subcate=>$v_subcate){
												if($v_subcate['id'] == $v['subcate_id']){
													echo $v_subcate['title'];
													break;
												}
											}
											?>
											</td>
											<td><a href="<?=$v['url']?>"><?=$v['url']?></a></td>
											<td>
												<button class="btn btn-small btn-primary btn-modify"
													data-toggle="modal" data-target="#myModal" id="update">修改</button>
												<button class="btn btn-small btn-danger" id="del">删除</button>
											</td>
										</tr>
									<?php }?>									
									</tbody>
								</table>
							</div>
							 <div class="pagination pagination-small pull-right">
                                <ul>
		                             <li><a href="naviitem?subcate_id=<?=$subcate_id?>&page=<?=$nowPage-1?>">Prev</a></li>
		                             	<?php if($numPages==1){?>
                                    <li class="page_btn active"><a href="naviitem?subcate_id=<?=$subcate_id?>" >1</a></li>
                                    <?php }else{?>
		                             <li class="page_btn <?php if($nowPage==1){echo "active";}?>">
		                             <a href="naviitem?subcate_id=<?=$subcate_id?>&page=1" >1</a>
		                             </li>
		                             <?php if ($nowPage>4) {?>
		                             <li><a>...</a></li>
		                             <?php }?>
		                             <?php for ($page = 2;$page < $numPages;$page ++){
											if (($page>=$nowPage-2)&&($page<=$nowPage+2)) {								
		                             	 ?>
		                             <li class="page_btn <?php if($page == $nowPage){echo "active";}?>">
		                             <a href="naviitem?subcate_id=<?=$subcate_id?>&page=<?=$page?>"><?=$page?></a>
		                             </li>
		                             <?php }}?>
		                             <?php if ($nowPage+3<$numPages) {?>
		                             <li><a>...</a></li>
		                             <?php }?>
		                             <li class="page_btn <?php if($nowPage==$numPages){echo "active";}?>">
		                             <a href="naviitem?subcate_id=<?=$subcate_id?>&page=<?=$numPages?>"><?=$numPages?></a>
		                             </li>  
		                             <?php }?>               
		                             <li><a href="naviitem?subcate_id=<?=$subcate_id?>&page=<?=$nowPage+1?>">Next</a></li>     
		                        </ul>
                            </div>
						</div>
						<!-- /block -->
					</div>
					<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
						aria-labelledby="myModalLabel" aria-hidden="true" style="display: none">
						<div class="row-fluid">
							<!-- block -->
							<!-- <div class="block"> -->
							<div class="block-content collapse in">
								<form class="form-horizontal">
									<fieldset>
										<legend>左屏导航网址</legend>
										<input type="hidden" id="idInput" value="">
										<div class="control-group">
											<label class="control-label" for="parentsSelect">所属子类</label>
											<div class="controls">
												<select id="parentsSelect">
												<?php foreach ($navisubcate as $k_subcate=>$v_subcate){?>
												<option value='<?=$v_subcate['id']?>'><?=$v_subcate['title']?></option>
												<?php }?>
												</select>
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="titleInput">网址名称</label>
											<div class="controls">
												<input class="input-xlarge focused" id="titleInput"
													type="text" value="2048朝代版">
											</div>
										</div>
										
										<div class="control-group">
											<label class="control-label" for="urlInput">网址地址</label>
											<div class="controls">
												<input class="input-xlarge " id="urlInput" type="url"
													value="http://2048.zerob13.in">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="titleInput">a_color</label>
											<div class="controls">
												<input class="input-xlarge focused" id="a_colorInput"
													type="text" value="">
											</div>
										</div><div class="control-group">
											<label class="control-label" for="titleInput">b_color</label>
											<div class="controls">
												<input class="input-xlarge focused" id="b_colorInput"
													type="text" value="">
											</div>
										</div>
										<div class="form-actions">
											<button type="submit" class="btn btn-primary" id="add_btn"
												data-dismiss="modal">保存</button>
											<button type="submit" class="btn btn-primary" id="update_btn"
												data-dismiss="modal">保存</button>
											<button type="reset" class="btn" data-dismiss="modal">取消</button>
										</div>
									</fieldset>
								</form>
							</div>
							<!-- </div> -->
							<!-- /block -->

						</div>
					</div>
				</div>
				<hr>
				<footer>
					<p>&copy; By Zerob13 2014</p>
				</footer>
			</div>
			<!--/.fluid-container-->
		</div>
	</div>
</body>

</html>