							<script src="../assets/home.js"></script>
							<div class="block">
							<div class="navbar navbar-inner block-header">
								<div class="muted pull-left">轻应用数据</div>
								<div class="pull-right">
									<span class="badge badge-info">最后修改日期: 2014-4-1 14:11</span>
								</div>
							</div>
							<div class="block-content collapse in">
								<table class="table table-striped">
									<thead>
										<tr>
											<th><button class="btn btn-small btn-info"
													data-toggle="modal" data-target="#myModal" id="add">添加</button>
											</th>
											<th>版本号</th>
											<th>最小版本号</th>
											<th>最大版本号</th>
											<th>命令</th>	
											<th>老地址</th>
											<th>地址</th>
											<th>路径</th>
											<th>颜色</th>
										</tr>
									</thead>
									<tbody class="drag_tr">
										<?php foreach ($homeoperation as $k=>$v){?>
										<tr>
											<td><?=$v['id']?></td>
											<td><?=$v['version']?></td>										
											<td><?=$v['version_min']?></td>
											<td><?=$v['version_max']?></td>
											<td><?=$v['command']?></td>
											<td><?=$v['old_url']?></td>
											<td><?=$v['url']?></td>
											<td><?=$v['src']?></td>
											<td><?=$v['color']?></td>
											<td>
												<button class="btn btn-small btn-primary btn-modify"
													data-toggle="modal" data-target="#myModal" id="update">修改</button>
												<button class="btn btn-small btn-danger" id="del">删除</button>
											</td>
										</tr>
										<?php }?>
										
									
									</tbody>
								</table>
							</div>
							 <div class="pagination pagination-small pull-right">
                                <ul>
                                    <li><a href="home?page=<?=$nowPage-1?>">Prev</a></li>
                                    <?php if($numPages==1){?>
                                    <li class="page_btn active"><a href="home" >1</a></li>
                                    <?php }else{?>
                                    <li class="page_btn <?php if($nowPage==1){echo "active";}?>">
		                             <a href="home?page=1" >1</a>
		                             </li>
		                             <?php if ($nowPage>4) {?>
		                             <li><a>...</a></li>
		                             <?php }?>
		                             <?php for ($page = 2;$page < $numPages;$page ++){
											if (($page>=$nowPage-2)&&($page<=$nowPage+2)) {								
		                             	 ?>
		                             <li class="page_btn <?php if($page == $nowPage){echo "active";}?>">
		                             <a href="home?page=<?=$page?>"><?=$page?></a>
		                             </li>
		                             <?php }}?>
		                             <?php if ($nowPage+3<$numPages) {?>
		                             <li><a>...</a></li>
		                             <?php }?>
		                             <li class="page_btn <?php if($nowPage==$numPages){echo "active";}?>">
		                             <a href="home?page=<?=$numPages?>"><?=$numPages?></a>
		                             </li> 
		                             <?php }?>                  
                                    <li><a href="home?page=<?=$nowPage+1?>">Next</a></li>
                                </ul>
                            </div>
						</div>