						<script src="../assets/liteitem.js"></script>
						<div class="block">
							<div class="navbar navbar-inner block-header">
								<div class="muted pull-left">轻应用数据</div>
								<div class="pull-right">
									<span class="badge badge-info">最后修改日期: 2014-4-1 14:11</span>
								</div>
							</div>
							<div class="block-content collapse in">
								<table class="table table-striped">
									<thead>
										<tr>
											<th><button class="btn btn-small btn-info"
													data-toggle="modal" data-target="#myModal" id="add">添加</button>
											</th>
											<th>应用名称</th>
											<th>所属类别</th>
											<th>应用URL</th>
											<th>icon</th>
											<th>应用描述</th>
											<th>下载量</th>
											<th>操作</th>
										</tr>
									</thead>
									<tbody>
									<?php foreach ($lite_item as $K=>$v){?>
									<tr>
											<td><?=$v['id']?></td>
											<td><?=$v['title']?></td>
											<td>
											<input type="hidden" value="<?=$v['category']?>" id='category'>
											<?php
												foreach ($lite_category as $k_cate=>$v_cate){
													if($v_cate['category'] == $v['category']){
														echo $v_cate['title'];
														break;
													}
												}
											?>
											</td>
											<td><a href="<?=$v['url']?>"><?=$v['url']?></a></td>
											<td><?=$v['img']?></td>
											<td><?=$v['dcrp']?></td>
											<td><?=$v['downloads']?></td>
											<td>
												<button class="btn btn-small btn-primary btn-modify"
													data-toggle="modal" data-target="#myModal" id='update'>修改</button>
												<button class="btn btn-small btn-danger" id='del'>删除</button>
											</td>
										</tr>
									<?php }?>
								</tbody>
								</table>
							</div>
							<div class="pagination pagination-small pull-right">
								<ul>
									<li>
										<a href="liteitem?category=<?=$category?>&page=<?=$nowPage-1?>">Prev</a>
									</li>
                             <?php if($numPages==1){?>
	                             <li class="page_btn active">
	                             	<a href="liteitemcategory=<?=$category?>">1</a>
	                             </li>
                             <?php }else{?>
                             <li class="page_btn <?php if($nowPage==1){echo "active";}?>">
                             	<a href="liteitem?category=<?=$category?>&page=1">1</a>
                             </li>
                             <?php if ($nowPage>4) {?>
                            	 <li><a>...</a></li>
                             <?php }?>
                             <?php for ($page = 2;$page < $numPages;$page ++){
									if (($page>=$nowPage-2)&&($page<=$nowPage+2)) {								
	                              ?>
                             	<li class="page_btn <?php if($page == $nowPage){echo "active";}?>">
										<a href="liteitem?category=<?=$category?>&page=<?=$page?>"><?=$page?></a>
									</li>
                             <?php }}?>
                             <?php if ($nowPage+3<$numPages) {?>
                            	 <li><a>...</a></li>
                             <?php }?>
                             	<li class="page_btn <?php if($nowPage==$numPages){echo "active";}?>">
										<a href="liteitem?category=<?=$category?>&page=<?=$numPages?>"><?=$numPages?></a>
									</li>   
                             <?php }?>              
                             	<li><a href="liteitem?category=<?=$category?>&page=<?=$nowPage+1?>">Next</a></li>
								</ul>
							</div>
						</div>