<!DOCTYPE html>
<html>
<head>
<title>数据后台登录</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
<meta name="description" content="绿茶浏览器数据后台">
<meta name="author" content="zerob13">
<!-- Bootstrap -->
<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link href="bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
<link href="assets/styles.css" rel="stylesheet" media="screen">
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
<script src="vendors/jquery-1.9.1.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript">
</script>
</head>
<body id="login">
<div class="container">
    <form class="form-signin" method="post" action="/core/version">
        <h2 class="form-signin-heading">输入咒语进入后台</h2>
        <input type="text" name="username" class="input-block-level" placeholder="用户名">
        <input type="password" name="userpasswd" class="input-block-level" placeholder="密码">
        <label class="checkbox">
            <input type="checkbox" value="remember-me">记住密码 
        </label>
        <button class="btn btn-large btn-primary" type="submit">提交</button>
    </form>

</div> <!-- /container -->
</body>
</html>